## 1. Data Import and Cleaning

In [11]:

import pandas as pd

df = pd.read_csv(r"C:\Users\syeda\Downloads\sample_data.csv")

# Drop rows with missing values
df_dropna = df.dropna()

# Replace missing numerical values with mean
df_fill_mean = df.copy()
df_fill_mean['C'] = df_fill_mean['C'].fillna(df_fill_mean['C'].mean())

# Replace missing categorical values with mode
df_fill_mode = df.copy()
df_fill_mode['E'] = df_fill_mode['E'].fillna(df_fill_mode['E'].mode()[0])

df_dropna, df_fill_mean, df_fill_mode


(    A   B     C    D      E        Date
 1  93  24  64.0  dog  apple  2023-01-02
 2  15   3  60.0  cat  apple  2023-01-03
 5  21   2  33.0  dog  apple  2023-01-06
 7  87  30  76.0  dog  apple  2023-01-08,
     A   B     C    D      E        Date
 0  52  88  52.0  cat    NaN  2023-01-01
 1  93  24  64.0  dog  apple  2023-01-02
 2  15   3  60.0  cat  apple  2023-01-03
 3  72  22  52.0  dog  apple  2023-01-04
 4  61  53  21.0  cat    NaN  2023-01-05
 5  21   2  33.0  dog  apple  2023-01-06
 6  83  88  52.0  cat  apple  2023-01-07
 7  87  30  76.0  dog  apple  2023-01-08
 8  75  38  58.0  cat    NaN  2023-01-09
 9  75   2  52.0  dog  apple  2023-01-10,
     A   B     C    D      E        Date
 0  52  88   NaN  cat  apple  2023-01-01
 1  93  24  64.0  dog  apple  2023-01-02
 2  15   3  60.0  cat  apple  2023-01-03
 3  72  22   NaN  dog  apple  2023-01-04
 4  61  53  21.0  cat  apple  2023-01-05
 5  21   2  33.0  dog  apple  2023-01-06
 6  83  88   NaN  cat  apple  2023-01-07
 7  87  30  76

## 2. Data Transformation

In [13]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df['A_plus_B'] = np.add(df['A'], df['B'])
df['sqrt_A'] = np.sqrt(df['A'])

scaler = MinMaxScaler()
df['A_normalized'] = scaler.fit_transform(df[['A']])

df[['A', 'B', 'A_plus_B', 'sqrt_A', 'A_normalized']]



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\syeda\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\syeda\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "c:\Users\syeda\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "c:\Users\syeda\anaconda3\Lib\site-packa

AttributeError: _ARRAY_API not found

ImportError: numpy.core.multiarray failed to import

## 3. Merging and Joining Datasets

In [14]:

df2 = df[['A', 'B']].copy()
df2['key'] = list(range(10))
df['key'] = list(range(10))

merged_df = pd.merge(df, df2, on='key', how='inner').fillna(0)

df_left = pd.DataFrame({'id': [1, 2], 'val1': ['x', 'y']})
df_right = pd.DataFrame({'ref': [2, 3], 'val2': ['a', 'b']})
left_join = pd.merge(df_left, df_right, left_on='id', right_on='ref', how='left')

df_concat = pd.concat([df, df2], axis=1)
df_concat = df_concat.loc[:, ~df_concat.columns.duplicated()]

merged_df, left_join, df_concat


(   A_x  B_x     C    D      E        Date  key  A_y  B_y
 0   52   88   0.0  cat      0  2023-01-01    0   52   88
 1   93   24  64.0  dog  apple  2023-01-02    1   93   24
 2   15    3  60.0  cat  apple  2023-01-03    2   15    3
 3   72   22   0.0  dog  apple  2023-01-04    3   72   22
 4   61   53  21.0  cat      0  2023-01-05    4   61   53
 5   21    2  33.0  dog  apple  2023-01-06    5   21    2
 6   83   88   0.0  cat  apple  2023-01-07    6   83   88
 7   87   30  76.0  dog  apple  2023-01-08    7   87   30
 8   75   38  58.0  cat      0  2023-01-09    8   75   38
 9   75    2   0.0  dog  apple  2023-01-10    9   75    2,
    id val1  ref val2
 0   1    x  NaN  NaN
 1   2    y  2.0    a,
     A   B     C    D      E        Date  key
 0  52  88   NaN  cat    NaN  2023-01-01    0
 1  93  24  64.0  dog  apple  2023-01-02    1
 2  15   3  60.0  cat  apple  2023-01-03    2
 3  72  22   NaN  dog  apple  2023-01-04    3
 4  61  53  21.0  cat    NaN  2023-01-05    4
 5  21   2  33.0  

## 4. Grouping and Aggregation

In [15]:

grouped = df.groupby('D')['A'].agg(['mean', 'std'])

sum_grouped = df.groupby('D')['A'].sum()
sum_grouped_np = np.sqrt(sum_grouped)

pivot_table = df.pivot_table(values='A', index='D', columns='E', aggfunc=np.mean)

grouped, sum_grouped_np, pivot_table


C:\Users\syeda\AppData\Local\Temp\ipykernel_8424\3371770286.py:6: FutureWarning: The provided callable <function mean at 0x00000233A12D3920> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot_table = df.pivot_table(values='A', index='D', columns='E', aggfunc=np.mean)


(     mean        std
 D                   
 cat  57.2  26.480181
 dog  69.6  28.492104,
 D
 cat    16.911535
 dog    18.654758
 Name: A, dtype: float64,
 E    apple
 D         
 cat   49.0
 dog   69.6)

## 5. Array Operations and Manipulation

In [16]:

arr = df['A'].values
arr_squared = arr ** 2

reshaped_arr = arr.reshape(-1, 1)
df['reshaped_A'] = reshaped_arr

filtered_df = df[df['A'] > 50]

arr_squared, reshaped_arr, filtered_df


(array([2704, 8649,  225, 5184, 3721,  441, 6889, 7569, 5625, 5625]),
 array([[52],
        [93],
        [15],
        [72],
        [61],
        [21],
        [83],
        [87],
        [75],
        [75]]),
     A   B     C    D      E        Date  key  reshaped_A
 0  52  88   NaN  cat    NaN  2023-01-01    0          52
 1  93  24  64.0  dog  apple  2023-01-02    1          93
 3  72  22   NaN  dog  apple  2023-01-04    3          72
 4  61  53  21.0  cat    NaN  2023-01-05    4          61
 6  83  88   NaN  cat  apple  2023-01-07    6          83
 7  87  30  76.0  dog  apple  2023-01-08    7          87
 8  75  38  58.0  cat    NaN  2023-01-09    8          75
 9  75   2   NaN  dog  apple  2023-01-10    9          75)

## 6. Broadcasting and Vectorized Operations

In [17]:

broadcast_array = np.array([1])
df['broadcasted'] = df['A'] + broadcast_array[0]

df['multi_column_sum'] = np.add(df['A'], df['B'])

row_means = df.iloc[:, 0:2].mean(axis=1)
df_broadcast = df.iloc[:, 0:2].subtract(row_means, axis=0)

df[['broadcasted', 'multi_column_sum']], df_broadcast


(   broadcasted  multi_column_sum
 0           53               140
 1           94               117
 2           16                18
 3           73                94
 4           62               114
 5           22                23
 6           84               171
 7           88               117
 8           76               113
 9           76                77,
       A     B
 0 -18.0  18.0
 1  34.5 -34.5
 2   6.0  -6.0
 3  25.0 -25.0
 4   4.0  -4.0
 5   9.5  -9.5
 6  -2.5   2.5
 7  28.5 -28.5
 8  18.5 -18.5
 9  36.5 -36.5)

## 7. Linear Algebra with NumPy

In [18]:

# Solve system: 2x + y = 8; 3x + 2y = 13
A_sys = np.array([[2, 1], [3, 2]])
b_sys = np.array([8, 13])
solution = np.linalg.solve(A_sys, b_sys)

df_dot = np.dot(df['A'], df['B'])

matrix_mult = pd.DataFrame(np.dot(df[['A', 'B']].values.T, df[['A', 'B']].values))

solution, df_dot, matrix_mult


(array([3., 2.]),
 np.int64(24626),
        0      1
 0  46632  24626
 1  24626  21718)

## 8. Handling Missing Data

In [19]:

df_interp = df.copy()
df_interp['C'] = df_interp['C'].interpolate(method='linear')

mask = df['C'].isna()
df_masked = df.copy()
df_masked['C'][mask] = -1

q1 = df['C'].quantile(0.25)
q3 = df['C'].quantile(0.75)
iqr = q3 - q1
outlier_mask = (df['C'] < (q1 - 1.5 * iqr)) | (df['C'] > (q3 + 1.5 * iqr))
df_outliers_handled = df.copy()
df_outliers_handled.loc[outlier_mask, 'C'] = df['C'].median()

df_interp, df_masked, df_outliers_handled


C:\Users\syeda\AppData\Local\Temp\ipykernel_8424\3310742839.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_masked['C'][mask] = -1
C:\Users\syeda\AppData\Local\Temp\ipykernel_8424\3310742839.py:6: SettingWithCopyWarning: 
A value is t

(    A   B     C    D      E        Date  key  reshaped_A  broadcasted  \
 0  52  88   NaN  cat    NaN  2023-01-01    0          52           53   
 1  93  24  64.0  dog  apple  2023-01-02    1          93           94   
 2  15   3  60.0  cat  apple  2023-01-03    2          15           16   
 3  72  22  40.5  dog  apple  2023-01-04    3          72           73   
 4  61  53  21.0  cat    NaN  2023-01-05    4          61           62   
 5  21   2  33.0  dog  apple  2023-01-06    5          21           22   
 6  83  88  54.5  cat  apple  2023-01-07    6          83           84   
 7  87  30  76.0  dog  apple  2023-01-08    7          87           88   
 8  75  38  58.0  cat    NaN  2023-01-09    8          75           76   
 9  75   2  58.0  dog  apple  2023-01-10    9          75           76   
 
    multi_column_sum  
 0               140  
 1               117  
 2                18  
 3                94  
 4               114  
 5                23  
 6               171  


## 9. Advanced Data Analysis

In [20]:

trend_df = df.groupby(['D', 'E'])['A'].mean().unstack()

correlation = df[['A', 'B', 'C']].corr()

df['rolling_mean'] = df['A'].rolling(window=3).mean()
df[['Date', 'A', 'rolling_mean']]


Date   A  rolling_mean
0  2023-01-01  52           NaN
1  2023-01-02  93           NaN
2  2023-01-03  15     53.333333
3  2023-01-04  72     60.000000
4  2023-01-05  61     49.333333
5  2023-01-06  21     51.333333
6  2023-01-07  83     55.000000
7  2023-01-08  87     63.666667
8  2023-01-09  75     81.666667
9  2023-01-10  75     79.000000

## 10. DataFrame and Array Manipulation

In [21]:

arr = df.values
arr += 1
df_transformed = pd.DataFrame(arr, columns=df.columns)

random_df = pd.DataFrame(np.random.rand(10, 3), columns=['X', 'Y', 'Z'])
filtered_random_df = random_df[(random_df['X'] > 0.5) & (random_df['Y'] < 0.5)]

arr1 = np.array(df['A'])
arr2 = np.array(df['B'])
df_custom = pd.DataFrame(np.power(arr1, 2) + np.power(arr2, 2), columns=['custom_sum'])

df_transformed, filtered_random_df, df_custom


TypeError: can only concatenate str (not "int") to str

## 11. Data Reshaping and Analysis

In [22]:

reshaped = df['A'].values.reshape(2, 5)

df1 = df.head(5)
df2 = df.tail(5)
stacked = pd.concat([df1, df2], axis=0)

array3d = np.random.randint(1, 10, size=(2, 3, 3))
df_3d = pd.DataFrame(array3d.reshape(6, 3))
df_grouped_3d = df_3d.groupby(df_3d.index % 2).sum()

reshaped, stacked, df_grouped_3d


(array([[52, 93, 15, 72, 61],
        [21, 83, 87, 75, 75]]),
     A   B     C    D      E        Date  key  reshaped_A  broadcasted  \
 0  52  88   NaN  cat    NaN  2023-01-01    0          52           53   
 1  93  24  64.0  dog  apple  2023-01-02    1          93           94   
 2  15   3  60.0  cat  apple  2023-01-03    2          15           16   
 3  72  22   NaN  dog  apple  2023-01-04    3          72           73   
 4  61  53  21.0  cat    NaN  2023-01-05    4          61           62   
 5  21   2  33.0  dog  apple  2023-01-06    5          21           22   
 6  83  88   NaN  cat  apple  2023-01-07    6          83           84   
 7  87  30  76.0  dog  apple  2023-01-08    7          87           88   
 8  75  38  58.0  cat    NaN  2023-01-09    8          75           76   
 9  75   2   NaN  dog  apple  2023-01-10    9          75           76   
 
    multi_column_sum  rolling_mean  
 0               140           NaN  
 1               117           NaN  
 2         

## 12. Time Series Analysis

In [23]:

df['Date'] = pd.to_datetime(df['Date'])
df['days_diff'] = (df['Date'] - df['Date'].shift()).dt.days.fillna(0)

df['moving_avg'] = df['A'].rolling(window=3).mean()

datetime_diff = df['Date'].diff().dt.days

df[['Date', 'A', 'moving_avg', 'days_diff']], datetime_diff


(        Date   A  moving_avg  days_diff
 0 2023-01-01  52         NaN        0.0
 1 2023-01-02  93         NaN        1.0
 2 2023-01-03  15   53.333333        1.0
 3 2023-01-04  72   60.000000        1.0
 4 2023-01-05  61   49.333333        1.0
 5 2023-01-06  21   51.333333        1.0
 6 2023-01-07  83   55.000000        1.0
 7 2023-01-08  87   63.666667        1.0
 8 2023-01-09  75   81.666667        1.0
 9 2023-01-10  75   79.000000        1.0,
 0    NaN
 1    1.0
 2    1.0
 3    1.0
 4    1.0
 5    1.0
 6    1.0
 7    1.0
 8    1.0
 9    1.0
 Name: Date, dtype: float64)